### ISSUE TITLE
Missing Pokemon

### ISSUE THREAD

**Issue by Cosmogriff** [ElChicoEevee/pkmnunite-assets#2]
Alolan Ninetales Theater Style is missing

**Comment by ElChicoEevee** [comment]
Updating it soon!

**Comment by Cosmogriff** [comment]
> Updating it soon!

The there are parts of the holowear texture that are transparent.

<img width="288" alt="1" src="https://user-images.githubusercontent.com/102986778/162433290-a961c34e-1c25-4803-a175-714c15b3c809.png">
![t_d_lob_003805_lv3](https://user-images.githubusercontent.com/102986778/162433314-e2c5b6e0-be9f-454e-842f-33a73f809b6f.png)

**Comment by ElChicoEevee** [comment]
Edit alpha channel

**Comment by Cosmogriff** [comment]
check
3D Assets/Pokemon/Lobby Models/Lv3/pref_char_lob_003805_ninetales_lv3/t_d_lob_003805_lv3.png
